Repository submariner-io/shipyard, pull requests merged in 2020-07, with the labels that each got.

#237 Add E2E job to test consuming projects
  .github/workflows/e2e-consuming.yaml
Labels: test-projects

#241 Show which golangci-lint linters are enabled
  scripts/shared/validate.sh
Labels: automation, cncf

#238 Add admiral to the e2e-consuming projects
  .github/workflows/e2e-consuming.yaml
Labels: test-projects

#244 Better Shipyard base image
  .github/workflows/release.yaml
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/build_image.sh
Labels: shipyard, test-projects

#252 Fix local image tag
  scripts/shared/build_image.sh
Labels: test-projects

#246 Allow validating consuming projects
  .github/workflows/e2e-consuming.yaml
  .github/workflows/validate-consuming.yaml
Labels: validate-projects

#245 Bump golangci-lint version from 1.26.0 to 1.28.0
  package/Dockerfile.shipyard-dapper-base
Labels: automation, cncf, validate-projects

#259 Update subctl version in base image to v0.5.0
  package/Dockerfile.shipyard-dapper-base
Labels: test-projects

#233 Upgrade to Kubernetes 1.15
  go.mod
  go.sum
  scripts/shared/clusters.sh
  scripts/shared/resources/kind-cluster-config.yaml
Labels: dependencies, technical-debt, test-projects

#253 Upgrade to Kubernetes 1.17
  go.mod
  go.sum
  scripts/shared/clusters.sh
  scripts/shared/resources/kind-cluster-config.yaml
Labels: test-projects
