Repository submariner-io/shipyard, pull requests merged in 2020-04, with the labels that each got.

#70 Add ability to specify nodes dynamically
  scripts/shared/clusters.sh
  scripts/shared/lib/cluster_settings
  scripts/shared/resources/kind-cluster-config.yaml
Labels: automation, shipyard

#81 Undeploy test resources once connectivity test succeeds
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_funcs
Labels: automation, shipyard

#87 Release properly
  .travis.yml
  Makefile
  Makefile.inc
  scripts/release
  scripts/shared/release.sh
Labels: automation, shipyard

#96 Use distinct names for release make target variables
  .travis.yml
  Makefile.inc
Labels: automation, shipyard

#109 Retry KIND deployment
  scripts/shared/clusters.sh
Labels: shipyard

#103 Add some basic documentation
  README.md
Labels: shipyard

#116 Fix double slash in SCRIPTS_DIR file paths
  package/Dockerfile.dapper-base
Labels: automation, bug

#114 Add RELEASE_ARGS for `release` target
  .travis.yml
  Dockerfile.dapper
  Makefile.inc
Labels: shipyard

#120 Make registry_inmemory a boolean flag
  Makefile.inc
  scripts/shared/clusters.sh
Labels: shipyard

#118 Make globalnet a boolean flag
  Makefile.inc
  scripts/shared/clusters.sh
Labels: shipyard

#124 Use new `--globalnet-cidr` flag
  package/Dockerfile.dapper-base
  scripts/shared/lib/deploy_operator
Labels: shipyard

#127 Added cluster funcs that abstract details
  scripts/shared/cleanup.sh
  scripts/shared/clusters.sh
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_helm
  scripts/shared/lib/deploy_operator
  scripts/shared/lib/utils
Labels: shipyard
