Repository submariner-io/shipyard, pull requests merged in 2020-11, with the labels that each got.

#352 Use single space vs tab alignment in CODEOWNERS.in
  CODEOWNERS.in
Labels: automation, documentation

#360 Switch to Helm v3
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/lib/deploy_helm
Labels: e2e-projects

#362 Fix release job, avoid deprecated set-env
  .github/workflows/release.yml
Labels: automation, dependencies

#367 Build with buildx, add platform support
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/build_image.sh
Labels: multiarch

#365 Add cable-driver support to using flag, add tests
  .github/workflows/consuming.yml
  Makefile.inc
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_helm
  scripts/shared/lib/deploy_operator
Labels: automation, e2e-projects

#371 Remove deprecated validate target
  Makefile
  Makefile.inc
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/lib/find_functions
  scripts/shared/validate.sh
Labels: automation
