Repository submariner-io/shipyard, pull requests merged in 2020-08, with the labels that each got.

#254 Turn the version script into a Makefile snippet
  .github/workflows/e2e-consuming.yaml
  .github/workflows/release.yaml
  .github/workflows/scripts.yaml
  .github/workflows/validations.yaml
  Makefile
  Makefile.inc
  Makefile.versions
  scripts/shared/lib/version
Labels: test-projects

#271 Increase consuming project validations 10m->15m
  .github/workflows/validate-consuming.yaml
Labels: automation, cncf

#273 Fix MD lint violations
  .markdownlint.yml
  README.md
Labels: automation, cncf, documentation

#272 Install markdownlint-cli, run in verify
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/validate.sh
Labels: automation, cncf, documentation, validate-projects

#281 Add commit message validations
  .github/workflows/gitlint.yaml
  .gitlint
  Makefile
  Makefile.inc
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/gitlint.sh
Labels: automation, cncf, documentation

#283 Add link aliveness tests
  .github/ISSUE_TEMPLATE/broken-link.md
  .github/workflows/md-links-periodic.yml
  .github/workflows/md-links.yml
  .markdownlinkcheck.json
Labels: automation, cncf, documentation

#288 Bump MD link check linter 0.6->1.*
  .github/workflows/md-links-periodic.yml
  .github/workflows/md-links.yml
Labels: automation, cncf, documentation

#290 Add YAML linting, fix errors
  .github/workflows/dco-check.yml
  .github/workflows/e2e-consuming.yml
  .github/workflows/gitlint.yml
  .github/workflows/md-links-periodic.yml
  .github/workflows/md-links.yml
  .github/workflows/release.yml
  .github/workflows/scripts.yml
  .github/workflows/validate-consuming.yml
  .github/workflows/validations.yml
  .github/workflows/yaml-lint.yml
  .markdownlint.yml
  .yamllint.yml
  scripts/shared/resources/kind-cluster-config.yaml
Labels: automation, cncf
