Repository submariner-io/shipyard, pull requests merged in 2020-05, with the labels that each got.

#131 Export kubeconfigs on dapper image
  package/Dockerfile.dapper-base
  scripts/shared/lib/kubecfg
  scripts/shared/lib/utils
Labels: shipyard

#132 Add post mortem script
  .travis.yml
  Makefile
  Makefile.inc
  scripts/shared/post_mortem.sh
Labels: shipyard

#147 Remove any selinux policy packages
  package/Dockerfile.dapper-base
Labels: shipyard

#113 Make the number of clusters configurable
  scripts/shared/cleanup.sh
  scripts/shared/clusters.sh
  scripts/shared/deploy.sh
  scripts/shared/lib/cluster_settings
  scripts/shared/lib/deploy_funcs
  scripts/shared/lib/utils
Labels: shipyard

#133 Clean out outputs on cleanup
  scripts/shared/cleanup.sh
Labels: shipyard

#156 Add --timeout flag to scripts
  .github/workflows/scripts.yaml
  .travis.yml
  scripts/shared/clusters.sh
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_funcs
Labels: shipyard

#159 Push the tag image last
  scripts/shared/release.sh
Labels: shipyard

#149 Remove GCC and related packages
  package/Dockerfile.dapper-base
Labels: shipyard

#151 Define broker in cluster_settings
  scripts/shared/clusters.sh
  scripts/shared/deploy.sh
  scripts/shared/lib/cluster_settings
  scripts/shared/lib/deploy_helm
Labels: shipyard

#165 Fix post_mortem script and add a test for it
  .github/workflows/scripts.yaml
  scripts/shared/post_mortem.sh
  test/scripts/post_mortem/test.sh
Labels: shipyard

#115 Add shared e2e.sh script
  .github/workflows/scripts.yaml
  .travis.yml
  Dockerfile.dapper
  Makefile
  Makefile.inc
  scripts/shared/e2e.sh
Labels: shipyard

#163 Use nettest image for netshoot pod
  test/e2e/framework/deployments.go
Labels: shipyard

#176 Fix KUBECONFIG var export help at end of deploys
  scripts/shared/lib/utils
Labels: bug

#172 Cache parent images also
  scripts/shared/build_image.sh
Labels: shipyard

#175 Add OLM install support to cluster deployments
  scripts/shared/clusters.sh
Labels: automation
