Repository submariner-io/shipyard, pull requests merged in 2020-10, with the labels that each got.

#324 Use standard "images" target vs "dapper-image"
  .github/workflows/e2e-consuming.yml
  .github/workflows/release.yml
  .github/workflows/scripts.yml
  .github/workflows/validate-consuming.yml
  Makefile
  Makefile.dapper
Labels: automation, cncf, documentation

#328 Bump SUBCTL_VERSION to 0.7.0-rc0
  package/Dockerfile.shipyard-dapper-base
Labels: test-projects

#337 Bump to subctl 0.7.0-rc2
  package/Dockerfile.shipyard-dapper-base
Labels: test-projects

#348 Add CI for CODEOWNERS generation
  .github/workflows/codeowners.yml
Labels: automation
