Repository submariner-io/shipyard, pull requests merged in 2020-09, with the labels that each got.

#293 Allow local yamllint
  .github/workflows/yaml-lint.yml
  .yamllint.yml
  Makefile.inc
  package/Dockerfile.shipyard-dapper-base
Labels: automation

#304 Remove dockerd
  package/Dockerfile.shipyard-dapper-base
Labels: test-projects, validate-projects

#311 Image shrinkage
  package/Dockerfile.shipyard-dapper-base
Labels: test-projects, validate-projects

#315 Add discrete Go and MD linting make targets
  .github/workflows/validations.yml
  Makefile
  Makefile.inc
Labels: automation, cncf

#318 Add "lint" make target to run all linters
  Makefile.inc
Labels: automation, cncf

#320 Add "unit" make target, will replace "unit-test"
  Makefile.inc
Labels: automation, cncf
