Repository submariner-io/shipyard, pull requests merged in 2020-12, with the labels that each got.

#377 Test the same cable drivers as consuming projects
  .github/workflows/consuming.yml
Labels: automation, e2e-projects

#388 Remove unused unit-test make target
  Makefile
  Makefile.inc
Labels: automation

#386 Update gitlint ignore for new Dependabot
  .gitlint
Labels: automation

#391 Add license headers to Go files
  test/e2e/dataplane/tcp_connectivity.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/example/example.go
  test/e2e/framework/api_errors.go
  test/e2e/framework/cleanup.go
  test/e2e/framework/deployments.go
  test/e2e/framework/exec.go
  test/e2e/framework/framework.go
  test/e2e/framework/ginkgo_framework.go
  test/e2e/framework/logging.go
  test/e2e/framework/network_pods.go
  test/e2e/framework/nodes.go
  test/e2e/framework/pods.go
  test/e2e/framework/services.go
  test/e2e/framework/test_context.go
  test/e2e/framework/util.go
  test/e2e/tcp/connectivity.go
  test/scripts/compile/hello.go
Labels: cncf
