Repository submariner-io/shipyard, pull requests merged in 2021-01, with the labels that each got.

#406 Import ovn-daemonset-f image
  scripts/shared/deploy.sh
Labels: OVN, backport

#409 Don't tag as `devel` by default
  .github/workflows/release.yml
  scripts/shared/release.sh
Labels: backport

#413 Pre-pull OVN image in clusters.sh
  scripts/shared/clusters.sh
  scripts/shared/deploy.sh
Labels: OVN, backport

#411 Use the PR base branch as reference when linting
  .github/workflows/linting.yml
Labels: backport

#422 Create prepare-host github actions
  .github/workflows/consuming.yml
  .github/workflows/upgrade-e2e.yml
  gh-actions/prepare-host/action.yaml
Labels: e2e-projects, validate-projects

#356 When deploying with Helm, use the operator
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_helm
Labels: operator

#426 Import the networkplugin-syncer correctly
  scripts/shared/deploy.sh
Labels: backport

#429 Bump golangci-lint to 1.36
  package/Dockerfile.shipyard-dapper-base
Labels: dependencies, lint-projects
