Repository submariner-io/shipyard, pull requests merged in 2021-11, with the labels that each got.

#663 Add support for YAML settings
  .shipyard.e2e.ovn.yml
  .shipyard.e2e.yml
  Makefile
  package/Dockerfile.shipyard-dapper-base
  scripts/cluster_settings
  scripts/cluster_settings.ovn
  scripts/shared/clusters.sh
  scripts/shared/deploy.sh
  scripts/shared/e2e.sh
  scripts/shared/lib/utils
Labels: e2e-projects

#594 Use our own implementation of Dapper
  .dapper
  .github/workflows/consuming.yml
  .gitignore
  Makefile.dapper
Labels: lint-projects, e2e-projects, unit-projects

#668 Drop `cluster_settings` support
  scripts/shared/clusters.sh
  scripts/shared/deploy.sh
  scripts/shared/e2e.sh
  scripts/shared/lib/cluster_settings
  scripts/shared/lib/utils
Labels: e2e-projects

#673 dapper: add project definition
  .dapper
Labels: lint-projects

#666 Upgrade to Fedora 35
  package/Dockerfile.shipyard-dapper-base
Labels: lint-projects, e2e-projects, unit-projects

#652 Update K8s versions: drop 1.17/1.18, add 1.21/1.22
  .github/workflows/consuming.yml
  gh-actions/e2e/action.yaml
Labels: e2e-projects

#665 Bump golangci-lint to 1.43.0
  package/Dockerfile.shipyard-dapper-base
Labels: lint-projects

#679 Bump Docker buildx to 0.7.0
  package/Dockerfile.shipyard-dapper-base
Labels: e2e-projects
