Repository submariner-io/shipyard, pull requests merged in 2021-09, with the labels that each got.

#630 Use SHAs for GHA versions
  .github/workflows/clean-tests.yml
  .github/workflows/codeowners.yml
  .github/workflows/consuming.yml
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
  .github/workflows/release.yml
  .github/workflows/scripts.yml
  .github/workflows/upgrade-e2e.yml
Labels: automation

#634 Handle vendoring in multiple Go modules
  Makefile
  Makefile.inc
Labels: unit-projects

#631 Implement .mdignore for ignoring Markdown files
  Makefile.inc
Labels: automation, lint-projects

#633 Run unit tests in multiple modules
  scripts/shared/lib/find_functions
  scripts/shared/unit_test.sh
Labels: unit-projects

#640 Update create-issue-from-file GHA 2.3.2 to 3.0.0
  .github/workflows/periodic.yml
Labels: automation

#628 Fix yamllint strict config, fail on warnings
  .yamllint.yml
  Makefile.inc
Labels: bug, automation, lint-projects

#639 Avoid deploying Lighthouse when not requested
  scripts/shared/lib/deploy_operator
Labels: automation, e2e-projects
