Repository submariner-io/shipyard, pull requests merged in 2021-08, with the labels that each got.

#617 Delete svcEx before Svc in e2e framework
  test/e2e/tcp/connectivity.go
Labels: globalnet, ready-to-test

#620 Don't run periodic PR dependency checks on forks
  .github/workflows/dependent-issues.yml
Labels: automation

#623 When deploying subctl, fall back to devel
  scripts/shared/deploy.sh
Labels: backport

#622 Install subctl as part of post_mortem
  scripts/shared/post_mortem.sh
Labels: ready-to-test

#629 Fix YAML linting warnings
  .github/dependabot.yml
  .github/workflows/dependent-issues.yml
  gh-actions/commit-size/action.yaml
  gh-actions/e2e/action.yaml
  gh-actions/post-mortem/action.yaml
  gh-actions/release-images/action.yaml
  gh-actions/upgrade-e2e/action.yaml
Labels: automation
