Repository submariner-io/shipyard, pull requests merged in 2021-03, with the labels that each got.

#462 refactor: rename submariner-engine to submariner-gateway
  scripts/shared/e2e.sh
  scripts/shared/lib/deploy_operator
  test/e2e/framework/framework.go
  test/e2e/framework/pods.go
Labels: e2e-projects

#465 Add `preload-images` target
  Makefile.inc
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_funcs
  scripts/shared/lib/deploy_operator
Labels: e2e-projects

#471 Allow unit-testing consuming projects
  .github/workflows/consuming.yml
Labels: unit-projects

#482 Remove obsolete E2E GHA inputs
  .yamllint.yml
  gh-actions/e2e/action.yaml
Labels: e2e-projects

#485 Rename clusters.sh version var to k8s_version
  scripts/shared/clusters.sh
Labels: automation

#486 Fix consuming project E2E, use using= flag for GHA
  .github/workflows/consuming.yml
Labels: automation

#466 Upgrade to kind 0.10
  .github/workflows/consuming.yml
  .github/workflows/scripts.yml
  Makefile
  Makefile.dapper
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/clusters.sh
  scripts/shared/resources/kind-cluster-config.yaml
Labels: e2e-projects

#487 Add k8s_version to shared E2E GHA options
  gh-actions/e2e/action.yaml
Labels: automation, e2e-projects

#492 Remove kind network workaround
  .github/workflows/consuming.yml
Labels: e2e-projects

#498 Show K8s client/server versions in post mortem
  scripts/shared/post_mortem.sh
Labels: automation

#496 Test additional K8s versions
  .github/workflows/consuming.yml
Labels: automation, dependencies, e2e-projects
