Repository submariner-io/shipyard, pull requests merged in 2021-04, with the labels that each got.

#513 Quick fix to ignore any devel versions
  Makefile.versions
Labels: e2e-projects

#514 Use a simpler version scheme
  .github/workflows/release.yml
  Makefile
  Makefile.inc
  Makefile.versions
Labels: e2e-projects

#519 Bump golangci-lint to 1.39.0
  package/Dockerfile.shipyard-dapper-base
Labels: lint-projects

#518 Add kube-controller-manager logs to postmortem
  scripts/shared/post_mortem.sh
Labels: automation

#532 Switch to subctl verify --kubecontexts
  scripts/shared/e2e.sh
Labels: e2e-projects

#533 Disable the DCO GHA
  .github/workflows/linting.yml
Labels: cncf

#535 Move non-verbose output out of AwaitFinishVerbose
  test/e2e/framework/network_pods.go
Labels: e2e-projects
