Repository submariner-io/shipyard, pull requests merged in 2021-05, with the labels that each got.

#541 Increase connect-timeout in benchmark tests
  test/e2e/framework/network_pods.go
Labels: backport

#536 Add the base branch as a container build argument
  scripts/shared/build_image.sh
Labels: automation

#539 Bump Go dependencies to Kubernetes 1.19
  go.mod
  go.sum
  test/e2e/example/example.go
  test/e2e/framework/deployments.go
  test/e2e/framework/framework.go
  test/e2e/framework/gateways.go
  test/e2e/framework/network_pods.go
  test/e2e/framework/nodes.go
  test/e2e/framework/pods.go
  test/e2e/framework/service_exports.go
  test/e2e/framework/services.go
Labels: dependencies

#549 Switch to k8s v1.20.2 by default
  scripts/shared/clusters.sh
Labels: bug, e2e-projects

#550 Don't run certain GHA jobs on forks
  .github/workflows/periodic.yml
  .github/workflows/release.yml
Labels: automation

#537 Bump to Fedora 34
  package/Dockerfile.shipyard-dapper-base
Labels: e2e-projects, lint-projects

#551 Fix double printing targets in Shipyard
  scripts/shared/targets.sh
Labels: backport

#553 Add VxLAN cable driver
  Makefile.inc
Labels: vxlan

#559 Refactor badges in README
  README.md
Labels: cncf, documentation

#561 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf, documentation, ready-to-test

#562 Enable custom pod to support HostNetworking
  test/e2e/framework/network_pods.go
Labels: ready-to-test

#558 Update the copyright statements to match CNCF recs
  .github/workflows/linting.yml
  .legal.json
  .licenserc.json
  test/e2e/dataplane/tcp_connectivity.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/example/example.go
  test/e2e/framework/api_errors.go
  test/e2e/framework/cleanup.go
  test/e2e/framework/deployments.go
  test/e2e/framework/docker.go
  test/e2e/framework/exec.go
  test/e2e/framework/framework.go
  test/e2e/framework/gateways.go
  test/e2e/framework/ginkgo_framework.go
  test/e2e/framework/logging.go
  test/e2e/framework/network_pods.go
  test/e2e/framework/nodes.go
  test/e2e/framework/pods.go
  test/e2e/framework/service_exports.go
  test/e2e/framework/services.go
  test/e2e/framework/test_context.go
  test/e2e/framework/util.go
  test/e2e/tcp/connectivity.go
  test/scripts/compile/hello.go
Labels: ready-to-test

#557 Test OVN on deploy job
  .github/workflows/scripts.yml
Labels: ready-to-test

#564 Linting in a small image
  Dockerfile.linting
  Makefile
  Makefile.dapper
  package/Dockerfile.shipyard-linting
Labels: lint-projects

#568 clusters.sh: support short K8s versions
  .github/workflows/consuming.yml
  gh-actions/e2e/action.yaml
  scripts/shared/clusters.sh
Labels: e2e-projects
