Repository submariner-io/shipyard, pull requests merged in 2021-06, with the labels that each got.

#573 Shared Dockerfile.dapper
  .github/workflows/scripts.yml
  Dockerfile.dapper
  Makefile
  Makefile.dapper
  README.md
  scripts/shared/release_images.sh
Labels: e2e-projects, lint-projects, unit-projects

#576 Copy Shipyard resources into consuming projects
  .github/workflows/consuming.yml
Labels: e2e-projects, lint-projects, unit-projects

#566 Bump to kind 0.11
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/clusters.sh
Labels: dependencies, e2e-projects

#591 Add linter to check no "Apply suggestions" commits
  .github/workflows/linting.yml
Labels: automation
