Repository submariner-io/shipyard, pull requests merged in 2021-02, with the labels that each got.

#425 Add E2E testing to composite actions
  .github/workflows/consuming.yml
  .github/workflows/upgrade-e2e.yml
  gh-actions/e2e/action.yaml
  gh-actions/prepare-host/action.yaml
  gh-actions/upgrade-e2e/action.yaml
Labels: e2e-projects

#431 Bump buildx to 0.5.1
  package/Dockerfile.shipyard-dapper-base
Labels: dependencies

#442 Tag released image with branch name
  .github/workflows/release.yml
Labels: backport

#444 Pin actions/checkout GHA to v2
  .github/workflows/upgrade-e2e.yml
Labels: automation

#438 Create composite `release-images` GitHub Action
  .github/workflows/release.yml
  Makefile
  Makefile.images
  Makefile.inc
  gh-actions/release-images/action.yaml
Labels: backport

#448 Improve post-mortem logging, list resources better
  scripts/shared/post_mortem.sh
Labels: automation

#449 Add Gateway functions to E2E framework
  test/e2e/framework/framework.go
  test/e2e/framework/gateways.go
  test/e2e/framework/ginkgo_framework.go
Labels: e2e-projects

#450 Use get.submariner.io to download subctl
  package/Dockerfile.shipyard-dapper-base
Labels: backport

#452 Use the right subctl version on image release
  .github/workflows/release.yml
  gh-actions/release-images/action.yaml
Labels: backport

#460 Always pull `subctl`
  .github/workflows/release.yml
  Makefile
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/deploy.sh
Labels: backport, e2e-projects

#420 Dump cluster info before deleting clusters
  scripts/shared/clusters.sh
Labels: e2e-projects, lint-projects

#458 When deploying with Helm, use the operator
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_helm
Labels: e2e-projects
