Repository submariner-io/shipyard, pull requests merged in 2022-02, with the labels that each got.

#712 Run subctl diagnose in post mortem
  scripts/shared/post_mortem.sh
Labels: automation

#719 Automated backport of #714: Increase inotify settings in E2E/upgrade GHAs
  gh-actions/e2e/action.yaml
  gh-actions/upgrade-e2e/action.yaml
Labels: automated-backport

#722 Clean Go caches once we've finished with them
  package/Dockerfile.shipyard-dapper-base
Labels: unit-projects

#725 Automated backport of #718: Refactor inotify E2E GHA step to be more standard
  gh-actions/e2e/action.yaml
  gh-actions/upgrade-e2e/action.yaml
Labels: automated-backport

#728 Handle full FROM syntax when listing cache images
  scripts/shared/build_image.sh
Labels: epic:multi-arch

#730 Reinstall .shflags if it's empty
  scripts/shared/lib/shflags
Labels: bug, automation

#729 Include Coastguard in `make prune-images`
  Makefile.dapper
Labels: bug, automation

#733 Update default K8s version 1.20 to 1.23
  scripts/shared/clusters.sh
Labels: automation

#735 Update Helm 3.7.1 to 3.8.0
  package/Dockerfile.shipyard-dapper-base
Labels: automation

#738 Test all Shipyard consumers in consuming-lint|unit
  .github/workflows/consuming.yml
Labels: automation

#736 Update gh CLI 2.2.0 to 2.5.1
  package/Dockerfile.shipyard-dapper-base
Labels: automation

#721 Build multi-arch images with buildx
  .github/workflows/multiarch.yml
  Makefile
  Makefile.images
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/build_image.sh
Labels: lint-projects, e2e-projects, unit-projects, epic:multi-arch

#732 Update shflags 1.0.3 to 1.2.3
  scripts/shared/lib/shflags
Labels: automation, lint-projects, e2e-projects, unit-projects

#741 Revert "Update shflags 1.0.3 to 1.2.3"
  scripts/shared/lib/shflags
Labels: e2e-projects
