Repository submariner-io/shipyard, pull requests merged in 2022-09, with the labels that each got.

#936 Don't preload any images in Shipyard
  Makefile.inc
Labels: e2e-projects

#938 Enable and fix shellcheck for some lib scripts
  scripts/shared/lib/cleanup_aws_ocp
  scripts/shared/lib/cleanup_kind
  scripts/shared/lib/clusters_aws_ocp
  scripts/shared/lib/clusters_kind
  scripts/shared/lib/ocp_utils
Labels: maintenance

#937 Preload `IMAGES` by default, allow extra
  Makefile
  Makefile.images
  scripts/shared/lib/deploy_operator
Labels: e2e-projects, maintenance

#939 Set `SHELLCHECK_ARGS` automatically
  Makefile
  Makefile.inc
Labels: lint-projects, maintenance

#942 Consolidate flag logic for deployment
  scripts/shared/lib/deploy_helm
  scripts/shared/lib/deploy_operator
Labels: e2e-projects, maintenance

#941 Test connectivity with Lighthouse if available
  scripts/shared/lib/deploy_funcs
Labels: maintenance

#950 Upgrade kind to 0.15, add K8s 1.25
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/lib/clusters_kind
Labels: e2e-projects, maintenance

#951 Add K8s 1.25 testing, use as default
  .github/workflows/consuming.yml
  Makefile.inc
Labels: maintenance

#952 Simplify scripts GHA matrix
  .github/workflows/scripts.yml
Labels: maintenance

#953 Add load balancer deployment support
  .github/workflows/scripts.yml
  Makefile.inc
  release-notes/20220919-load-balancer.md
  scripts/shared/lib/clusters_kind
  scripts/shared/lib/deploy_helm
  scripts/shared/lib/deploy_operator
Labels: release-note-handled
