Repository submariner-io/shipyard, pull requests merged in 2022-10, with the labels that each got.

#968 Use nettest image from quay for dummy pod
  scripts/shared/resources/dummypod.yaml
Labels: ready-to-test

#975 Automated backport of #967: Fix flaky e2e failures with kindnet cni
  .shipyard.e2e.yml
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_funcs
  scripts/shared/reload_images.sh
  scripts/shared/resources/dummypod.yaml
Labels: automated-backport

#976 Automated backport of #967: Fix flaky e2e failures with kindnet cni
  .shipyard.e2e.yml
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_funcs
  scripts/shared/resources/dummypod.yaml
Labels: automated-backport

#979 [Backport] Deploy dummypod ds even on control-nodes
  scripts/shared/resources/dummypod.yaml
Labels: automated-backport

#978 [Backport] Deploy dummypod ds even on control-nodes
  scripts/shared/resources/dummypod.yaml
Labels: automated-backport

#980 Display nodeName of connectorPod in e2e tests
  test/e2e/framework/network_pods.go
  test/e2e/tcp/connectivity.go
Labels: backport

#982 Remove stale globalnet e2e code
  test/e2e/dataplane/tcp_connectivity.go
  test/e2e/framework/services.go
  test/e2e/tcp/connectivity.go
Labels: e2e-projects

#992 Use the base branch when linting
  Dockerfile.linting
Labels: lint-projects, backport, maintenance

#940 Support for air-gapped KIND environment
  .github/workflows/scripts.yml
  Makefile
  Makefile.inc
  release-notes/20220911-air-gapped-kind.md
  scripts/shared/cloud-prepare.sh
  scripts/shared/clusters.sh
  scripts/shared/lib/clusters_kind
  scripts/shared/lib/deploy_funcs
  scripts/shared/lib/deploy_helm
  scripts/shared/lib/deploy_operator
  scripts/shared/lib/utils
  scripts/shared/resources/dummypod.yaml
Labels: release-note-needed, release-note-handled

#997 Preload `nettest` image when deploying on KIND
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_funcs
Labels: e2e-projects, ready-to-test

#994 Add issues:write permission to broken links GHA
  .github/workflows/periodic.yml
Labels: automation
