Repository submariner-io/shipyard, pull requests merged in 2022-12, with the labels that each got.

#1056 Cause dependabot to do all go updates once a week
  .github/dependabot.yml
Labels: automation

#1063 Use klog/v2 instead of v1
  go.mod
  go.sum
  test/e2e/e2e.go
  test/e2e/framework/test_context.go
Labels: dependencies, maintenance

#1064 Automated backport of #1062: Do not skip "master" nodes for non-gw nodes search
  test/e2e/framework/nodes.go
Labels: automated-backport

#1070 Bump to Kubernetes 0.26 dependencies
  go.mod
  go.sum
  test/e2e/framework/exec.go
  test/e2e/framework/framework.go
  test/e2e/framework/gateways.go
  test/e2e/framework/network_pods.go
  test/e2e/framework/nodes.go
Labels: dependencies

#1072 Bump GH CLI to v2.20.2
  package/Dockerfile.shipyard-dapper-base
Labels: ready-to-test

#1082 Add `TEST_ARGS` variable and fail fast E2E on CI
  Dockerfile.dapper
  Makefile.inc
  gh-actions/e2e/action.yaml
  scripts/shared/e2e.sh
Labels: e2e-projects, backport

#1085 [Backport 0.14] Add `TEST_ARGS` variable and fail fast E2E on CI
  Dockerfile.dapper
  Makefile.inc
  gh-actions/e2e/action.yaml
  scripts/shared/e2e.sh
Labels: e2e-projects

#1087 Drop older kind versions
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/lib/clusters_kind
Labels: e2e-projects

#1084 Remove globalnet flag from E2E
  scripts/shared/e2e.sh
  test/e2e/framework/framework.go
  test/e2e/framework/test_context.go
Labels: maintenance

#1083 Don't set skip default in E2E composite GHA
  gh-actions/e2e/action.yaml
Labels: e2e-projects, maintenance

#1074 Drop netshoot and nginx deployment code
  test/e2e/framework/deployments.go
Labels: lint-projects, e2e-projects, unit-projects
