Repository submariner-io/shipyard, pull requests merged in 2022-07, with the labels that each got.

#862 Bump Helm to 3.9.0
  package/Dockerfile.shipyard-dapper-base
Labels: dependencies

#855 Allow specifying HELM repo location
  scripts/shared/lib/deploy_helm
Labels: e2e-projects

#854 Update shflags 1.0.3 to 1.2.3
  scripts/shared/lib/shflags
Labels: e2e-projects

#867 Bump x/text to address CVE-2021-38561
  go.mod
  go.sum
Labels: backport

#870 Bump golangci-lint to 1.46.2
  package/Dockerfile.shipyard-dapper-base
Labels: dependencies, lint-projects, maintenance

#873 Create unit test coverage report
  scripts/shared/unit_test.sh
Labels: unit-projects, maintenance

#880 Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: backport, maintenance

#879 Automated backport of #874: Fix new markdownlint link error in README
  README.md
Labels: automated-backport

#877 Automated backport of #867: Bump x/text to address CVE-2021-38561
  go.mod
  go.sum
Labels: automated-backport

#883 Automated backport of #874: Fix new markdownlint link error in README
  README.md
Labels: automated-backport

#881 Automated backport of #880: Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: automated-backport

#882 Automated backport of #880: Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: automated-backport

#885 Rename coverprofile to already-ignored IDE pattern
  scripts/shared/unit_test.sh
Labels: maintenance

#886 Remove `registry_inmemory` flag
  scripts/shared/clusters.sh
Labels: e2e-projects
