Repository submariner-io/shipyard, pull requests merged in 2022-05, with the labels that each got.

#779 Show golangci-lint version in make target
  Makefile.inc
Labels: maintenance

#788 Add Dependabot updates of GitHub Actions
  .github/dependabot.yml
Labels: maintenance

#794 [Backport] Stop augmenting versions for `deploy-latest`
  Makefile.inc
  scripts/shared/lib/deploy_funcs
  scripts/shared/lib/deploy_operator
Labels: automated-backport

#808 Automated backport of #802: Mark the source directory as safe
  Dockerfile.dapper
  Dockerfile.linting
Labels: automated-backport

#812 Bump golangci-lint to 1.46.0
  package/Dockerfile.shipyard-dapper-base
Labels: dependencies, lint-projects, maintenance

#818 Automated backport of #809: Bump markdown-link-check to the current tip
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
Labels: automated-backport

#819 Use Dependabot to update GHAs on release-0.12
  .github/dependabot.yml
Labels: maintenance

#826 Clarify logged inotify warning
  scripts/shared/clusters.sh
Labels: maintenance

#828 Bump Docker buildx to 0.8.2
  package/Dockerfile.shipyard-dapper-base
Labels: maintenance

#830 Quote parameter expansions
  scripts/shared/backport.sh
  scripts/shared/build_image.sh
  scripts/shared/cleanup.sh
  scripts/shared/clusters.sh
  scripts/shared/compile.sh
  scripts/shared/deploy.sh
  scripts/shared/e2e.sh
  scripts/shared/entry
  scripts/shared/post_mortem.sh
  scripts/shared/release_images.sh
  scripts/shared/reload_images.sh
  scripts/shared/targets.sh
  scripts/shared/unit_test.sh
Labels: e2e-projects

#832 Fix unit test directory finding
  scripts/shared/lib/find_functions
  scripts/shared/unit_test.sh
Labels: unit-projects
