Repository submariner-io/shipyard, pull requests merged in 2022-01, with the labels that each got.

#692 Handle local builds in our Dapper infrastructure
  Makefile.dapper
Labels: lint-projects, e2e-projects, unit-projects

#707 Clarify backport script fail on fork name
  scripts/shared/backport.sh
Labels: automation

#710 Provide the correct uid/gid in rootless containers
  .dapper
Labels: lint-projects, unit-projects
