Repository submariner-io/shipyard, pull requests merged in 2022-08, with the labels that each got.

#894 Use BuildKit for `.dapper` build
  .dapper
Labels: maintenance

#896 Remove directories when cleaning
  Makefile.inc
Labels: maintenance

#893 Extract `get-subctl.sh` to easily fetch `subctl`
  Makefile.inc
  package/Dockerfile.shipyard-dapper-base
  release-notes/get-subctl
  scripts/shared/deploy.sh
  scripts/shared/get-subctl.sh
  scripts/shared/post_mortem.sh
Labels: e2e-projects, maintenance

#897 Shrink base image
  package/Dockerfile.shipyard-dapper-base
Labels: lint-projects, e2e-projects, unit-projects

#895 Support multi arch compile inside `compile.sh`
  scripts/shared/compile.sh
  test/scripts/compile/test.sh
Labels: maintenance

#891 Remove `shflags` entirely
  .gitignore
  Makefile.images
  Makefile.inc
  release-notes/removed-shflags
  scripts/shared/cleanup.sh
  scripts/shared/clusters.sh
  scripts/shared/compile.sh
  scripts/shared/deploy.sh
  scripts/shared/e2e.sh
  scripts/shared/lib/deploy_funcs
  scripts/shared/lib/shflags
  scripts/shared/lib/utils
  scripts/shared/release_images.sh
  test/scripts/compile/test.sh
Labels: lint-projects, e2e-projects, unit-projects

#906 Convert env vars to args in `build_image.sh`
  Makefile.images
  scripts/shared/build_image.sh
Labels: e2e-projects

#899 Bump golangci-lint 1.46.2 -> 1.47.3
  package/Dockerfile.shipyard-dapper-base
Labels: lint-projects, maintenance

#859 Default to Kubernetes 1.24
  Makefile.inc
Labels: e2e-projects

#909 Remove E2E_ARGS, get from settings
  Dockerfile.dapper
  Makefile
  Makefile.inc
  scripts/shared/e2e.sh
Labels: e2e-projects

#856 Adding basic scale testing capability
  .shipyard.scale.yml
  Makefile
  Makefile.inc
  scripts/shared/clusters.sh
  scripts/shared/deploy.sh
  scripts/shared/lib/utils
Labels: blocked-on-rereview

#919 Stop using deprecated --ikeport
  scripts/shared/lib/deploy_operator
Labels: maintenance

#921 Only check out ovn-kubernetes contrib and dist
  scripts/shared/clusters.sh
Labels: e2e-projects

#918 Extract `exit_error` and `expect_env` functions
  scripts/shared/build_image.sh
  scripts/shared/cloud-prepare.sh
  scripts/shared/clusters.sh
  scripts/shared/compile.sh
  scripts/shared/deploy.sh
  scripts/shared/e2e.sh
  scripts/shared/lib/deploy_bundle
  scripts/shared/lib/deploy_funcs
  scripts/shared/lib/deploy_ocm
  scripts/shared/lib/utils
  scripts/shared/release_images.sh
  test/scripts/compile/test.sh
  test/scripts/post_mortem/test.sh
Labels: lint-projects, e2e-projects, unit-projects, maintenance
