Repository submariner-io/shipyard, pull requests merged in 2022-06, with the labels that each got.

#840 Make weave deploy more robust
  scripts/shared/clusters.sh
Labels: e2e-projects

#849 Automated backport of #847: Label e2e test namespace as privileged
  test/e2e/framework/framework.go
Labels: automated-backport

#848 Allow dependabot upgrades on release-0.13
  .github/dependabot.yml
Labels: dependencies

#850 Automated backport of #847: Label e2e test namespace as privileged
  test/e2e/framework/framework.go
Labels: e2e-projects, automated-backport

#853 Remove `deploytool_.*_args`
  scripts/shared/deploy.sh
  scripts/shared/lib/deploy_helm
  scripts/shared/lib/deploy_operator
Labels: maintenance
