Repository submariner-io/shipyard, pull requests merged in 2022-03, with the labels that each got.

#737 Update yq 4.14.1 to 4.20.2
  package/Dockerfile.shipyard-dapper-base
Labels: automation, lint-projects, e2e-projects

#749 Drop the bundle and OCM deployment tests
  .github/workflows/scripts.yml
Labels: backport

#751 Include cloud-prepare in `make prune-images`
  Makefile.dapper
Labels: automation

#752 Remove K8s 1.20 tests as it's EOL
  .github/workflows/consuming.yml
Labels: automation

#746 Make golangci-lint a no-op if unconfigured
  Makefile.inc
Labels: lint-projects

#734 Update golangci-lint 1.43.0 to 1.44.2
  package/Dockerfile.shipyard-dapper-base
  test/e2e/framework/util.go
Labels: automation, lint-projects

#758 Bump kind to v0.12.0
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/clusters.sh
Labels: dependencies
