Repository submariner-io/shipyard, pull requests merged in 2022-11, with the labels that each got.

#1009 Set SecurityContext for nettest pod images
  test/e2e/framework/framework.go
  test/e2e/framework/network_pods.go
Labels: backport

#1011 Automated backport of #1009: Set SecurityContext for nettest pod images
  test/e2e/framework/framework.go
  test/e2e/framework/network_pods.go
Labels: automated-backport

#1013 Add K8s 1.25 (OCP 4.12) support for OCP installs
  scripts/shared/lib/ocp_utils
Labels: maintenance

#1019 Automated backport of #992: Use the base branch when linting
  Dockerfile.linting
Labels: automated-backport

#1018 Change air-gap invocation condition
  scripts/shared/lib/clusters_kind
Labels: backport

#1020 Automated backport of #1018: Change air-gap invocation condition
  scripts/shared/lib/clusters_kind
Labels: automated-backport

#1022 [Backport] Display nodeName of connectorPod in e2e tests
  test/e2e/framework/network_pods.go
  test/e2e/tcp/connectivity.go
Labels: automated-backport

#1025 Automated backport of #1024: Disable OCP namespace pod security label sync
  test/e2e/framework/framework.go
Labels: automated-backport

#1017 Deploy `dummypod` as part of kind clusters
  scripts/shared/deploy.sh
  scripts/shared/lib/clusters_kind
  scripts/shared/lib/deploy_funcs
  scripts/shared/resources/dummypod.yaml
Labels: e2e-projects, backport

#1028 Bump kind to 0.17
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/lib/clusters_kind
Labels: e2e-projects

#1045 Automated backport of #1024: Disable OCP namespace pod security label sync
  test/e2e/framework/framework.go
Labels: automated-backport

#1044 Automated backport of #1009: Set SecurityContext for nettest pod images
  go.mod
  go.sum
  test/e2e/framework/framework.go
  test/e2e/framework/network_pods.go
Labels: automated-backport

#1027 Bump to Fedora 37
  package/Dockerfile.shipyard-dapper-base
Labels: lint-projects, e2e-projects, unit-projects

#1049 Include context info while running post-mortem
  scripts/shared/post_mortem.sh
Labels: bug, ready-to-test

#1053 Pass make options in flags instead of env vars
  .github/workflows/clean-tests.yml
  .github/workflows/scripts.yml
  gh-actions/e2e/action.yaml
  gh-actions/release-images/action.yaml
Labels: e2e-projects
