Repository submariner-io/shipyard, pull requests merged in 2023-12, with the labels that each got.

#1475 Update K8s versions tested in E2E
  .github/workflows/consuming.yml
  Makefile.inc
Labels: automation, e2e-projects, ready-to-test

#1510 Automated backport of #1499: Fix linting image build failure due to PEP 668
  package/Dockerfile.shipyard-linting
Labels: automated-backport

#1511 Automated backport of #1226: Pin markdownlint-cli version #1228: Pin gitlint version #1499: Fix linting image build failure due to PEP 668
  package/Dockerfile.shipyard-linting
Labels: automated-backport

#1512 Automated backport of #1226: Pin markdownlint-cli version #1228: Pin gitlint version #1499: Fix linting image build failure due to PEP 668
  package/Dockerfile.shipyard-linting
Labels: automated-backport

#1513 Automated backport of #1226: Pin markdownlint-cli version #1228: Pin gitlint version #1499: Fix linting image build failure due to PEP 668
  package/Dockerfile.shipyard-linting
Labels: automated-backport

#1500 Bump markdownlint-cli to 0.38.0
  package/Dockerfile.shipyard-linting
Labels: lint-projects
