Repository submariner-io/shipyard, pull requests merged in 2023-09, with the labels that each got.

#1364 Use the tools module to build go-mod-outdated
  .github/workflows/periodic.yml
Labels: automation

#1114 Use local `Shipyard` when testing consuming E2E
  .github/workflows/consuming.yml
  Makefile.inc
  gh-actions/e2e/action.yaml
Labels: automation, e2e-projects

#1373 Use a specific OVNK commit
  scripts/shared/lib/clusters_kind
Labels: ready-to-test

#1377 Configure dependabot for the release-0.16 branch
  .github/dependabot.yml
Labels: automation

#1374 Automated backport of #1373: Use a specific OVNK commit
  scripts/shared/lib/clusters_kind
Labels: ready-to-test, automated-backport
