Repository submariner-io/shipyard, pull requests merged in 2023-04, with the labels that each got.

#1205 Give the full path to restore-images in e2e
  gh-actions/e2e/action.yaml
Labels: e2e-projects

#1204 Bump golangci-lint to 1.52.2
  package/Dockerfile.shipyard-dapper-base
Labels: lint-projects

#1220 Bump kind to 0.18.0
  package/Dockerfile.shipyard-dapper-base
  scripts/shared/lib/clusters_kind
Labels: dependencies, e2e-projects

#1225 Don't fail when restoring images if there are none
  gh-actions/restore-images/action.yaml
Labels: automation

#1226 Pin markdownlint-cli version
  package/Dockerfile.shipyard-linting
Labels: automation

#1223 Bump to Fedora 38
  package/Dockerfile.shipyard-dapper-base
Labels: dependencies, lint-projects, e2e-projects, unit-projects

#1228 Pin gitlint version
  package/Dockerfile.shipyard-linting
Labels: automation

#1229 Update Helm version to 3.11.3, fix CVEs
  package/Dockerfile.shipyard-dapper-base
Labels: dependencies

#1231 Update gh and yq
  package/Dockerfile.shipyard-dapper-base
Labels: dependencies
