Repository submariner-io/shipyard, pull requests merged in 2023-11, with the labels that each got.

#1459 Fix nil interface{} checks
  test/e2e/framework/clusterglobalegressip.go
  test/e2e/framework/framework.go
  test/e2e/framework/gateways.go
  test/e2e/framework/globalingressips.go
  test/e2e/framework/pods.go
Labels: backport

#1460 Automated backport of #1459: Fix nil interface{} checks
  test/e2e/framework/clusterglobalegressip.go
  test/e2e/framework/framework.go
  test/e2e/framework/gateways.go
  test/e2e/framework/globalingressips.go
  test/e2e/framework/pods.go
Labels: automated-backport

#1465 Various updates to fix CVEs
  tools/go.mod
  tools/go.sum
Labels: ready-to-test, security

#1466 Bump to Fedora 39
  package/Dockerfile.shipyard-dapper-base
  package/j2
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: e2e-projects

#1473 Update goproxy to fix GHSA-4r8x-2p26-976p
  go.mod
  go.sum
Labels: security

#1472 Update goproxy to fix GHSA-4r8x-2p26-976p
  go.mod
  go.sum
Labels: security

#1474 Switch from stale app to stale GHA
  .github/stale.yml
  .github/workflows/stale.yml
Labels: automation

#1297 Bump to kind 0.20.0
  scripts/shared/lib/clusters_kind
  tools/go.mod
  tools/go.sum
Labels: e2e-projects
