Repository submariner-io/shipyard, pull requests merged in 2024-04, with the labels that each got.

#1615 Update protobuf to 1.33.0 for CVE-2024-24786
  tools/go.mod
  tools/go.sum
Labels: security

#1616 Update protobuf to 1.33.0 for CVE-2024-24786
  tools/go.mod
  tools/go.sum
Labels: security

#1614 Update protobuf to 1.33.0 for CVE-2024-24786
  go.mod
  go.sum
Labels: unit-projects, ready-to-test, security

#1618 Bump helm/docker for CVE-2019-25210/CVE-2024-24557
  tools/go.mod
  tools/go.sum
Labels: security

#1617 Bump helm/docker for CVE-2019-25210/CVE-2024-24557
  tools/go.mod
  tools/go.sum
Labels: security

#1621 Bump to Fedora 40
  package/Dockerfile.shipyard-dapper-base
Labels: lint-projects, e2e-projects, unit-projects
