Repository submariner-io/shipyard, pull requests merged in 2024-02, with the labels that each got.

#1547 Bump to kind 0.21 and default to k8s 1.29
  .github/workflows/consuming.yml
  Makefile.clusters
  gh-actions/e2e/action.yaml
  scripts/shared/lib/clusters_kind
  tools/go.mod
  tools/go.sum
Labels: e2e-projects

#1541 Automated backport of #1223: Bump to Fedora 38
  package/Dockerfile.shipyard-dapper-base
Labels: lint-projects, e2e-projects, automated-backport

#1562 Bump helm from 3.14.0 to 3.14.1 for CVE-2024-25620
  tools/go.mod
  tools/go.sum
Labels: security

#1563 Bump helm from 3.12.3 to 3.14.1 for CVE-2024-25620
  tools/go.mod
  tools/go.sum
Labels: security

#1564 Automated backport of #1539: Prevent parallel cleanup of kind clusters
  scripts/shared/lib/cleanup_kind
Labels: automated-backport

#1566 Automated backport of #1558: Bump actions/cache
  gh-actions/cache-images/action.yaml
  gh-actions/restore-images/action.yaml
Labels: automated-backport

#1568 Automated backport of #1558: Bump actions/cache
  gh-actions/cache-images/action.yaml
  gh-actions/restore-images/action.yaml
Labels: automated-backport

#1567 Automated backport of #1558: Bump actions/cache
  gh-actions/cache-images/action.yaml
  gh-actions/restore-images/action.yaml
Labels: automated-backport

#1550 Bump golangci-lint to 1.56.2
  test/e2e/e2e.go
  test/e2e/framework/clusterglobalegressip.go
  test/e2e/framework/framework.go
  test/e2e/framework/gateways.go
  test/e2e/framework/globalingressips.go
  test/e2e/framework/pods.go
  tools/go.mod
  tools/go.sum
Labels: lint-projects
