Repository submariner-io/shipyard, pull requests merged in 2024-03, with the labels that each got.

#1582 Automated backport of #1572: Bump helm.sh/helm/v3 from 3.14.1 to 3.14.2 in /tools
  tools/go.mod
  tools/go.sum
Labels: automated-backport

#1585 Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: backport

#1591 Automated backport of #1585: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: automated-backport

#1593 Automated backport of #1585: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: automated-backport

#1594 Automated backport of #1585: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: automated-backport

#1600 Linting: handle existing workspaces
  Makefile.linting
Labels: lint-projects

#1605 Update markdownlint-cli to 0.39.0
  package/Dockerfile.shipyard-linting
Labels: automation, lint-projects

#1604 Update dependences of our custom GH actions
  gh-actions/cache-images/action.yaml
  gh-actions/post-mortem/action.yaml
  gh-actions/release-images/action.yaml
  gh-actions/restore-images/action.yaml
Labels: automation
