Repository submariner-io/shipyard, pull requests merged in 2025-04, with the labels that each got.

#1903 [0.20] Bump oauth2 to 0.27.0 for CVE-2025-22868
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: security

#1906 [0.17] Bump oauth2 to 0.27.0 for CVE-2025-22868
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: security

#1907 [0.16] Bump oauth2 to 0.27.0 for CVE-2025-22868
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: security

#1900 Annotate IPv4 and IPv6 addresses in air-gap
  scripts/shared/cloud-prepare.sh
Labels: ready-to-test

#1902 Bump oauth2 to 0.27.0 for CVE-2025-22868
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: ready-to-test, security

#1908 Pass --air-gapped flag to 'subctl join' if enabled
  scripts/shared/lib/deploy_operator
Labels: ready-to-test

#1905 [0.18] Bump oauth2 to 0.27.0 for CVE-2025-22868
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: blocked-on-rereview, security

#1912 Automated backport of #1911: Copy GITHUB_BASE_REF in the build container
  Dockerfile.dapper
Labels: automated-backport

#1916 Automated backport of #1911: Copy GITHUB_BASE_REF in the build container
  Dockerfile.dapper
Labels: automated-backport

#1914 Automated backport of #1911: Copy GITHUB_BASE_REF in the build container
  Dockerfile.dapper
Labels: automated-backport

#1920 Bump to Fedora 42
  package/Dockerfile.nettest
  package/Dockerfile.shipyard-dapper-base
Labels: lint-projects

#1928 Bump helm to 3.17.3 in /tools for CVE-2025-32387
  tools/go.mod
  tools/go.sum
Labels: security

#1936 Bump containerd to 1.7.27 and containerd/v2 2.0.4 for CVE-2024-40635
  tools/go.mod
  tools/go.sum
Labels: security

#1933 Bump containerd to 1.7.27 and containerd/v2 2.0.4 for CVE-2024-40635
  tools/go.mod
  tools/go.sum
Labels: e2e-projects, security

#1939 Bump containerd to 1.7.27 for CVE-2024-40635
  tools/go.mod
  tools/go.sum
Labels: security

#1954 Ignore Helm CVEs that require K8s major bump
  .grype.yaml
Labels: security

#1953 Ignore Helm CVEs that require K8s major bump
  .grype.yaml
Labels: security

#1951 Ignore Helm CVEs that require K8s major bump
  .grype.yaml
Labels: security

#1941 Bump buildx to 0.21.3 for CVE-2025-0495
  tools/go.mod
  tools/go.sum
Labels: security

#1950 Ignore buildx CVE that requires K8s major bump
  .grype.yaml
Labels: security

#1949 Ignore buildx CVE that requires K8s major bump
  .grype.yaml
Labels: security

#1948 Ignore buildx CVE that requires K8s major bump
  .grype.yaml
Labels: security
