Repository submariner-io/shipyard, pull requests merged in 2025-03, with the labels that each got.

#1869 Automated backport of #1868: Bump golang.org/x/net from 0.35.0 to 0.36.0
  go.mod
  go.sum
Labels: automated-backport

#1875 Automated backport of #1728: Bump to Fedora 41
  package/Dockerfile.shipyard-dapper-base
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: lint-projects, automated-backport

#1879 Automated backport of #1828: Bump custom GHA actions/cache from 4.0.2 to 4.2.0
  gh-actions/cache-images/action.yaml
  gh-actions/restore-images/action.yaml
Labels: automated-backport

#1880 Automated backport of #1828: Bump custom GHA actions/cache from 4.0.2 to 4.2.0
  gh-actions/cache-images/action.yaml
  gh-actions/restore-images/action.yaml
Labels: automated-backport

#1870 Automated backport of #1868: Bump golang.org/x/net from 0.35.0 to 0.36.0
  go.mod
  go.sum
Labels: automated-backport

#1876 Automated backport of #1728: Bump to Fedora 41
  package/Dockerfile.shipyard-dapper-base
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: automated-backport

#1877 Automated backport of #1728: Bump to Fedora 41
  package/Dockerfile.shipyard-dapper-base
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: automated-backport

#1872 Automated backport of #1868: Bump golang.org/x/net from 0.35.0 to 0.36.0
  go.mod
  go.sum
Labels: automated-backport

#1893 Ignore Konflux bot PRs in gitlint
  .gitlint
Labels: ready-to-test
